spring:
  config:
    activate:
      on-profile: test

jwt:
  secret: "testSecretKeyForJwtTokenGenerationThatShouldBeAtLeast64Characters!!"
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
