spring:
  config:
    activate:
      on-profile: local

jwt:
  secret: "mySecretKeyForJwtTokenGenerationThatShouldBeChangedInProductionEnvironment"
  access-token-expiration: 3600000  # 1시간 (밀리초)
  refresh-token-expiration: 604800000  # 7일 (밀리초) 
