spring:
  config:
    activate:
      on-profile: test

file:
  upload:
    base-path: ${java.io.tmpdir}/meet-again-test/uploads

backup:
  local:
    base-path: ${java.io.tmpdir}/meet-again-test/backups
