CREATE TABLE MEMBERS
(
    MEMBER_ID          BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- MemberTable 특화 컬럼들
    EMAIL              VARCHAR(255) NOT NULL,
    PASSWORD           VARCHAR(255) NOT NULL,
    NICKNAME           VARCHAR(255) NOT NULL,
    PHONE_NUMBER       VARCHAR(255) NOT NULL,
    NAME               VARCHAR(255) NOT NULL,
    BIRTH_DATE         DATE         NOT NULL,
    REGION             VARCHAR(255) NOT NULL,
    HIGH_SCHOOL        VARCHAR(255) NULL,
    UNIVERSITY         VARCHAR(255) NULL,
    PROFILE_IMAGE_URL  VARCHAR(255) NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255) DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255) DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN      DEFAULT FALSE,

    -- 인덱스
    UNIQUE INDEX idx_email (EMAIL)
);

-- REFRESH TOKENS
CREATE TABLE REFRESH_TOKENS
(
    REFRESH_TOKEN_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- RefreshToken 특화 컬럼들
    EMAIL              VARCHAR(255) NOT NULL,
    TOKEN              VARCHAR(1024) NOT NULL,
    EXPIRATION_DATE    DATETIME     NOT NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255) DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255) DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN      DEFAULT FALSE,

    -- 제약조건
    CONSTRAINT fk_refresh_tokens_member_email FOREIGN KEY (EMAIL) REFERENCES MEMBERS (EMAIL),

    -- 인덱스
    UNIQUE INDEX idx_refresh_token_token (TOKEN),
    INDEX idx_refresh_token_email (EMAIL)
);
