CREATE TABLE MEMBERS
(
    MEMBER_ID          BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- MemberTable 특화 컬럼들
    EMAIL              VARCHAR(255) NOT NULL,
    PASSWORD           VARCHAR(255) NOT NULL,
    NICKNAME           VARCHAR(255) NOT NULL,
    GENDER             VARCHAR(32)  NOT NULL,
    PHONE_NUMBER       VARCHAR(255) NOT NULL,
    NAME               VARCHAR(255) NOT NULL,
    REGION             VARCHAR(255) NOT NULL,
    BIRTH_DATE         DATE         NOT NULL,
    HIGH_SCHOOL        VARCHAR(255) NULL,
    UNIVERSITY         VARCHAR(255) NULL,
    PROFILE_IMAGE_URL  VARCHAR(255) NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255) DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255) DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN      DEFAULT FALSE,

    -- 인덱스
    UNIQUE INDEX idx_email (EMAIL)
);

-- REFRESH TOKENS
CREATE TABLE REFRESH_TOKENS
(
    REFRESH_TOKEN_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- RefreshToken 특화 컬럼들
    EMAIL              VARCHAR(255) NOT NULL,
    TOKEN              VARCHAR(1024) NOT NULL,
    EXPIRATION_DATE    DATETIME     NOT NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255) DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255) DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN      DEFAULT FALSE,

    -- 인덱스
    UNIQUE INDEX idx_refresh_token_token (TOKEN),
    INDEX idx_refresh_token_email (EMAIL)
);

-- TARGET INFOS
CREATE TABLE TARGET_INFOS
(
    TARGET_INFO_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- TargetInfoTable 특화 컬럼들
    REGISTER_EMAIL     VARCHAR(255) NOT NULL,
    NAME               VARCHAR(255) NOT NULL,
    TARGET_GENDER      VARCHAR(32)  NOT NULL,
    MIDDLE_NUMBER      VARCHAR(255) NULL,
    LAST_NUMBER        VARCHAR(255) NULL,
    `YEAR`             INT          NULL,
    `MONTH`            INT          NULL,
    `DAY`              INT          NULL,
    REGION             VARCHAR(255) NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255) DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255) DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN      DEFAULT FALSE,

    -- 인덱스
    INDEX idx_target_info_register_email (REGISTER_EMAIL)
);

-- MATCHING RESULTS
CREATE TABLE MATCHING_RESULTS
(
    MATCHING_RESULT_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- MatchingResultTable 특화 컬럼들
    REGISTER_EMAIL        VARCHAR(255) NOT NULL,
    TARGET_INFO_ID        BIGINT       NOT NULL,
    TARGET_EMAIL          VARCHAR(255) NOT NULL,
    MIDDLE_NUMBER_MATCHED BOOLEAN      NOT NULL,
    LAST_NUMBER_MATCHED   BOOLEAN      NOT NULL,
    YEAR_MATCHED          BOOLEAN      NOT NULL,
    MONTH_MATCHED         BOOLEAN      NOT NULL,
    DAY_MATCHED           BOOLEAN      NOT NULL,
    REGION_MATCHED        BOOLEAN      NOT NULL,
    SHOWING_EXPIRY_DATE   DATETIME     NOT NULL,
    MATCHING_EXPIRY_DATE  DATE         NOT NULL,
    EXCLUDED              BOOLEAN      DEFAULT FALSE,

    -- BaseTable 공통 컬럼들
    CREATED_DATE          DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY            VARCHAR(255) DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE    DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY      VARCHAR(255) DEFAULT 'MEET_AGAIN',
    DELETED               BOOLEAN      DEFAULT FALSE,

    -- 인덱스
    INDEX idx_matching_expiry_date (MATCHING_EXPIRY_DATE),
    INDEX idx_matching_register_email (REGISTER_EMAIL)
);

-- MEMBER PHOTOS
CREATE TABLE MEMBER_PHOTOS
(
    MEMBER_PHOTO_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- MemberPhotoTable 특화 컬럼들
    MEMBER_EMAIL       VARCHAR(255) NOT NULL,
    FILE_PATH          VARCHAR(512) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL,
    APPROVAL_STATUS    VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    THUMBNAIL_PATH     VARCHAR(512) NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255) DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255) DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN      DEFAULT FALSE,

    -- 인덱스
    INDEX idx_member_photo_email (MEMBER_EMAIL)
);

-- COMMUNITY POSTS
CREATE TABLE COMMUNITY_POSTS
(
    COMMUNITY_POST_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- PostTable 특화 컬럼들
    AUTHOR_EMAIL       VARCHAR(255)  NOT NULL,
    CATEGORY           VARCHAR(32)   NOT NULL,
    TITLE              VARCHAR(100)  NOT NULL,
    CONTENT            TEXT          NOT NULL,
    LIKES              INT           DEFAULT 0,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME      DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN       DEFAULT FALSE,

    -- 인덱스
    INDEX idx_community_post_category (CATEGORY),
    INDEX idx_community_post_author_email (AUTHOR_EMAIL)
);

-- COMMUNITY COMMENTS
CREATE TABLE COMMUNITY_COMMENTS
(
    COMMUNITY_COMMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- CommentTable 특화 컬럼들
    POST_ID              BIGINT        NOT NULL,
    AUTHOR_EMAIL         VARCHAR(255)  NOT NULL,
    CONTENT              TEXT          NOT NULL,
    PARENT_COMMENT_ID    BIGINT        NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE         DATETIME      DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY           VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE   DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY     VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    DELETED              BOOLEAN       DEFAULT FALSE,

    LIKES                INT           DEFAULT 0,

    -- 인덱스
    INDEX idx_community_comment_post_id (POST_ID),
    INDEX idx_community_comment_parent_id (PARENT_COMMENT_ID)
);

-- COMMUNITY COMMENT LIKES
CREATE TABLE COMMUNITY_COMMENT_LIKES
(
    COMMUNITY_COMMENT_LIKE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- CommentLikeTable 특화 컬럼들
    COMMENT_ID                BIGINT        NOT NULL,
    MEMBER_EMAIL              VARCHAR(255)  NOT NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE              DATETIME      DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY                VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE        DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY          VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    DELETED                   BOOLEAN       DEFAULT FALSE,

    -- 인덱스
    UNIQUE INDEX idx_comment_like_comment_member (COMMENT_ID, MEMBER_EMAIL),
    INDEX idx_comment_like_member_email (MEMBER_EMAIL)
);

-- COMMUNITY POST LIKES
CREATE TABLE COMMUNITY_POST_LIKES
(
    COMMUNITY_POST_LIKE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- PostLikeTable 특화 컬럼들
    POST_ID                BIGINT        NOT NULL,
    MEMBER_EMAIL           VARCHAR(255)  NOT NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE           DATETIME      DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY             VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE     DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY       VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    DELETED                BOOLEAN       DEFAULT FALSE,

    -- 인덱스
    UNIQUE INDEX idx_post_like_post_member (POST_ID, MEMBER_EMAIL),
    INDEX idx_post_like_member_email (MEMBER_EMAIL)
);

-- INQUIRIES
CREATE TABLE INQUIRIES
(
    INQUIRY_ID         BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- InquiryTable 특화 컬럼들
    AUTHOR_EMAIL       VARCHAR(255)  NOT NULL,
    TITLE              VARCHAR(100)  NOT NULL,
    CONTENT            VARCHAR(1500) NOT NULL,

    -- BaseTable 공통 컬럼들
    CREATED_DATE       DATETIME      DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY         VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    LAST_MODIFIED_DATE DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_MODIFIED_BY   VARCHAR(255)  DEFAULT 'MEET_AGAIN',
    DELETED            BOOLEAN       DEFAULT FALSE,

    -- 인덱스
    INDEX idx_inquiry_author_email (AUTHOR_EMAIL)
);
